### PR TITLE
Jaivasani patch1

### PR DESCRIPTION
**Pull request by jaivasani**

### CODE REVIEW

**Comment by thewhitetulip** [comment]
Thank you! I would like to know feedback about the book if you are willing to give :)

**Comment by jaivasani** [comment]
I'm not sure if there is a dedicated feedback section. So I am writing my feedback here.

The book and the videos were really helpful in learning python. (Thanks for that!)

The only place I had trouble was in executing the first python program.
1. I am using **windows** and to run python program I had to type **py filename.py** instead of **python filename.py**. It would would be helpful if you can mention about **py** in the description somewhere.

2. It took me a while to figure out how to install **iPython** package using the **pip**. Then it took me a while to figure out what pip command to use to install the package and if it was actually the correct command to install. A small step-by-step instructions on what commands to type in command prompt would be really helpful for someone who is new to command line.

3. You might want to check your **10-task.md** file. In the **remove()** function
```
## snippet
elif command == "remove":
	try:
		file = open("tasks.txt", "r")
	except IOError as e:
		print(str(e))
		sys.exit(1)
	
	tasks = file.readlines()
	tasks = [task.strip() for task in tasks]
	task_id = args[2]
	del tasks[int(task_id)]
```
Here we are deleting the task from the tasks list. But after we delete the task, we are not updating the text file. Hence, when we run the **list** command, the list command still shows all the tasks including the one which we had previously deleted from the list. 
It would be nice if you can add a code to write to file before the program ends or before the remove function ends.

Thanks,
Jai

**Comment by thewhitetulip** [comment]
Thank you, I'll start a new issue about feedback!

I use mac and had no idea to this point that we can run code like `py file.py`

I am going to change the remove() function. The thing is, I have made massive changes to the earlier chapters, chapters from the functions are left.

**Comment by thewhitetulip** [comment]
#35 Is the issue about feedback, I am copy pasting your above feedback there. Also, spread the word about this book and video series!

**Pull request merged**
